export type Task = {
  id: string | number;
  title?: string;
  reference_code?: string | null;
  movement_type?: string | null;
  description?: string | null;
  status: string;
  priority?: string;
  quantity?: number;
  sku?: string | null;
  product_name?: string | null;
  warehouse_name?: string | null;
  warehouse_code?: string | null;
  source_warehouse_name?: string | null;
  destination_warehouse_name?: string | null;
  notes?: string | null;
  projectId?: string | number | null;
  project_id?: string | number | null;
  project?: string | null;
  projectName?: string | null;
  project_name?: string | null;
  assigneeId?: string | number | null;
  assignee_id?: string | number | null;
  assignee?: string | null;
  assigneeName?: string | null;
  assignee_name?: string | null;
  created_at?: string | null;
};

export type StatusFilter = "all" | "draft" | "completed" | "cancelled";
export type PriorityFilter = "all" | "inbound" | "outbound" | "transfer" | "adjustment";
