import Link from "next/link";
import ProjectEditForm from "./ProjectEditForm";
import type { Project } from "./types";
import { FormEvent } from "react";

export default function ProjectCard({ project, canManage, isEditing, editName, editDescription, actionError, isSaving, isDeleting, onStartEdit, onDelete, onEditNameChange, onEditDescriptionChange, onEditSubmit, onCancelEdit }: { project: Project; canManage: boolean; isEditing: boolean; editName: string; editDescription: string; actionError: string; isSaving: boolean; isDeleting: boolean; onStartEdit: (project: Project) => void; onDelete: (projectId: string | number) => void; onEditNameChange: (value: string) => void; onEditDescriptionChange: (value: string) => void; onEditSubmit: (event: FormEvent<HTMLFormElement>, projectId: string | number) => void; onCancelEdit: () => void; }) {
  const ownerLabel = project.owner?.trim() || project.owner_username?.trim() || project.owner_name?.trim() || project.owner_email?.trim() || `Owner #${project.owner_id}`;
  return <article className="rounded-3xl border border-[var(--border-soft)] bg-[var(--surface-2)] p-5 sm:p-6">{isEditing ? <ProjectEditForm projectId={project.id} editName={editName} editDescription={editDescription} actionError={actionError} isSaving={isSaving} onEditNameChange={onEditNameChange} onEditDescriptionChange={onEditDescriptionChange} onSubmit={onEditSubmit} onCancel={onCancelEdit} /> : <><h3 className="text-2xl font-semibold tracking-tight text-zinc-900"><Link href={`/projects/${project.id}`} className="inline-flex items-center gap-1.5 transition-colors hover:text-[var(--brand-red-strong)] focus:outline-none focus:ring-2 focus:ring-[var(--brand-red-soft)]">{project.name}</Link></h3><p className="mt-3 text-sm leading-6 text-zinc-700">{project.description?.trim() ? project.description : "No description"}</p><p className="mt-4 text-xs uppercase tracking-wide text-zinc-500">Owner: {ownerLabel}</p><p className="mt-1 text-xs uppercase tracking-wide text-zinc-500">Created: {new Date(project.created_at).toLocaleString()}</p>{canManage && <div className="mt-5 flex flex-wrap gap-2.5"><button type="button" onClick={() => onStartEdit(project)} className="rounded-full border border-[var(--border-soft)] bg-[var(--surface)] px-4 py-2 text-sm font-medium text-zinc-700 transition hover:bg-white focus:outline-none focus:ring-2 focus:ring-[var(--brand-red-soft)]">Edit</button><button type="button" onClick={() => onDelete(project.id)} disabled={isDeleting} className="rounded-full border border-[var(--brand-red-border)] bg-[var(--brand-red)] px-4 py-2 text-sm font-medium text-white transition hover:bg-[var(--brand-red-strong)] focus:outline-none focus:ring-2 focus:ring-[var(--brand-red-soft)] disabled:opacity-60">{isDeleting ? "Deleting..." : "Delete"}</button></div>}{actionError && <p className="mt-2 text-sm text-red-600">{actionError}</p>}</>}</article>;
}
